guid: 00305300013aa532          # (defaults to first camera on bus)
video_mode: format7_mode0
frame_id: basler_a622f

# set some feature values:
auto_brightness: 3      #Manual 
brightness: 8
auto_exposure: 5        #None 
exposure: 0
auto_gain: 3            #Manual 
gain: 150
auto_shutter: 3         #Manual
shutter: 1200

