#guid: 305300013aa532          # (defaults to first camera on bus)
video_mode: format7_mode0
frame_id: basler_a622f
camera_info_url: file:///cameras/basler_a622f_calibration.yaml

# Set exposure values:
auto_brightness: 3      #Manual 
brightness: 0
auto_exposure: 5        #None 
exposure: 0
auto_gain: 3            #Manual 
gain: 100
auto_shutter: 3         #Manual
shutter: 512

